POST http://localhost:8080/api/login
content-type: application/json

{
  "password": "012345",
  "email": "pawel@example.com"
}

###

POST http://localhost:8080/api/users
content-type: application/json

{
  "password": "012345",
  "email": "pawel@example.com"
}

###

POST http://localhost:8080/api/chirps
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiI0MzQwNjQyNi0wMDcyLTRhOWMtODUxNy0zYjQ0YmY3ZWM3NmMiLCJpYXQiOjE3NjYzNTYwMjAsImV4cCI6MTc2NjM1OTYyMH0.2OjAvLcKz4qyXKsaPCuBtGFe1aopiOzF9Lrt1UPqxIQ

{
  "body": "Chirp2"
}